# Generated by Django 5.2.8 on 2026-01-18 14:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
        ('oshis', '0005_oshi_met_day_alter_oshi_group_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='oshi_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='oshis.oshi'),
        ),
    ]
