# Generated by Django 5.2.8 on 2026-01-18 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_event_oshi_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='iamge',
            field=models.ImageField(blank=True, null=True, upload_to='event_images/'),
        ),
    ]
