# Generated by Django 5.2.8 on 2026-01-18 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_event_iamge'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='iamge',
            new_name='image',
        ),
    ]
