# Generated by Django 5.2.8 on 2026-01-23 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_rename_iamge_event_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='image',
            new_name='event_image',
        ),
        migrations.AddField(
            model_name='event',
            name='goods_image',
            field=models.ImageField(blank=True, null=True, upload_to='goods_list_images/'),
        ),
    ]
