# Generated by Django 5.2.8 on 2026-01-15 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oshis', '0002_alter_oshi_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='oshi',
            name='aniversary',
            field=models.DateField(blank=True, null=True),
        ),
    ]
