# Generated by Django 5.2.8 on 2026-01-16 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oshis', '0003_oshi_aniversary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='oshi',
            name='oshi_id',
        ),
        migrations.AddField(
            model_name='oshi',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
