# Generated by Django 5.2.8 on 2026-01-28 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oshis', '0005_oshi_met_day_alter_oshi_group_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='oshi',
            name='color',
            field=models.CharField(default='#666666', max_length=7),
        ),
    ]
