# Generated by Django 5.2.8 on 2026-02-02 06:03

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oshis', '0006_oshi_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oshi',
            name='met_day',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
