# Generated by Django 5.2.8 on 2026-01-15 15:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Oshi',
            fields=[
                ('oshi_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('group_name', models.CharField(max_length=20, null=True)),
                ('birthday', models.DateField(blank=True, null=True)),
                ('category', models.CharField(choices=[('artist', 'アーティスト'), ('vocaloid', 'ボーカロイド'), ('character', 'キャラクター'), ('vtuber', 'Vチューバー'), ('idol', 'アイドル'), ('performer', '演者'), ('other', 'その他')], default='未設定', max_length=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to='oshi_icons/')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oshis', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
