# Generated by Django 5.2.8 on 2026-01-15 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oshis', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oshi',
            name='category',
            field=models.CharField(choices=[('artist', 'アーティスト'), ('activist', '配信者'), ('vocaloid', 'ボーカロイド'), ('character', 'キャラクター'), ('vtuber', 'Vチューバー'), ('idol', 'アイドル'), ('performer', '演者'), ('other', 'その他')], default='未設定', max_length=20),
        ),
    ]
