# Generated by Django 5.2.8 on 2026-01-16 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oshis', '0004_remove_oshi_oshi_id_oshi_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='oshi',
            name='met_day',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='oshi',
            name='group_name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
