# Generated by Django 5.2.8 on 2026-01-18 14:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('oshis', '0005_oshi_met_day_alter_oshi_group_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('goods_id', models.AutoField(primary_key=True, serialize=False)),
                ('good_name', models.CharField(max_length=20)),
                ('price', models.DecimalField(decimal_places=0, max_digits=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to='goods_images/')),
                ('memo', models.TextField(blank=True, null=True)),
                ('oshi_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oshis.oshi')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goods', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
