# Generated by Django 5.2.8 on 2026-01-20 03:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_rename_iamge_event_image'),
        ('goods', '0002_goods_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='category',
            field=models.CharField(choices=[('acrylic_keyholder', 'アクキー'), ('acrylic_stand', 'アクスタ'), ('badge', '缶バッジ'), ('figure', 'フィギュア'), ('disc', 'CD・DVD・BD'), ('book', '書籍'), ('other', 'その他')], default='other', max_length=20),
        ),
        migrations.AddField(
            model_name='goods',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='goods', to='events.event'),
        ),
        migrations.AddField(
            model_name='goods',
            name='total_price',
            field=models.PositiveIntegerField(default=1, editable=False),
            preserve_default=False,
        ),
    ]
