# Generated by Django 5.2.8 on 2026-01-20 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0003_goods_category_goods_event_goods_total_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='total_price',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
    ]
