# Generated by Django 5.2.8 on 2026-01-20 04:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_rename_iamge_event_image'),
        ('goods', '0004_alter_goods_total_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goods',
            name='oshi_id',
        ),
        migrations.AlterField(
            model_name='goods',
            name='event',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='goods', to='events.event'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='total_price',
            field=models.DecimalField(decimal_places=0, default=0, editable=False, max_digits=10),
        ),
    ]
