# Generated by Django 5.2.8 on 2026-01-20 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0005_remove_goods_oshi_id_alter_goods_event_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='goods',
            old_name='good_name',
            new_name='goods_name',
        ),
    ]
