# Generated by Django 5.2.8 on 2026-01-23 03:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_rename_image_event_event_image_event_goods_image'),
        ('goods', '0006_rename_good_name_goods_goods_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='goods',
            old_name='image',
            new_name='goods_image',
        ),
        migrations.AlterField(
            model_name='goods',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goods', to='events.event'),
        ),
    ]
