# Generated by Django 5.2.8 on 2026-01-18 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('money', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenditure',
            name='category',
            field=models.CharField(choices=[('goods', 'グッズ'), ('superchat', 'スパチャ'), ('other', 'その他')], max_length=20),
        ),
    ]
