# Generated by Django 5.2.8 on 2026-01-19 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('money', '0002_alter_expenditure_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='income',
            name='type',
            field=models.CharField(choices=[('salary', '給料'), ('bonus', 'ボーナス'), ('gift', 'ギフト'), ('other', 'その他')], default=1, max_length=20),
            preserve_default=False,
        ),
    ]
